rules:
- id: SecretKeySpec
  pattern-either:
    - pattern: new SecretKeySpec(new String("...").getBytes(), "...")
    - pattern: new SecretKeySpec("...".getBytes(), "...")
  languages: 
    - java
  message: |
    SecretKeySpec
  severity: WARNING