rules:
- id: getCategories
  pattern-either:
    - patterns:
      - pattern: $Y.$FUNC(...)
      - pattern-inside: |
          $RETVAL $FUN(...) {
            ...
            $Y = getIntent().getCategories();
            ...
          }
      - pattern-not-inside: |
          $RETVAL $FUN(...) {
            ...
            $Y = getIntent().getCategories();
            ...
            if ($Y != null) {
              ...
            }
            ...
          }
    - patterns:
      - pattern: getIntent().getCategories().$FUNC(...)
    - patterns:
      - pattern: $Y.$FUNC(...)
      - pattern-inside: |
          $RETVAL $FUN(..., Intent $X, ...) {
            ...
            $Y = (Intent $X).getCategories();
            ...
          }
      - pattern-not-inside: |
          $RETVAL $FUN(..., Intent $X, ...) {
            ...
            $Y = (Intent $X).getCategories();
            ...
            if ($Y != null) {
              ...
            }
            ...
          }
    - patterns:
      - pattern: (Intent $X).getCategories().$FUNC(...)
      - pattern-inside: |
          $RETVAL $FUN(..., Intent $X, ...) {
            ...
          }
  languages: 
    - java
  message: |
    getCategories
  severity: WARNING