rules:
- id: getDataString
  pattern-either:
    - patterns:
      - pattern: $Y.$FUNC(...)
      - pattern-inside: |
          $RETVAL $FUN(...) {
            ...
            $Y = getIntent().getDataString();
            ...
          }
      - pattern-not-inside: |
          $RETVAL $FUN(...) {
            ...
            $Y = getIntent().getDataString();
            ...
            if ($Y != null) {
              ...
            }
            ...
          }
    - patterns:
      - pattern: getIntent().getDataString().$FUNC(...)
    - patterns:
      - pattern: $Y.$FUNC(...)
      - pattern-inside: |
          $RETVAL $FUN(..., Intent $X, ...) {
            ...
            $Y = (Intent $X).getDataString();
            ...
          }
      - pattern-not-inside: |
          $RETVAL $FUN(..., Intent $X, ...) {
            ...
            $Y = (Intent $X).getDataString();
            ...
            if ($Y != null) {
              ...
            }
            ...
          }
    - patterns:
      - pattern: (Intent $X).getDataString().$FUNC(...)
      - pattern-inside: |
          $RETVAL $FUN(..., Intent $X, ...) {
            ...
          }
  languages: 
    - java
  message: |
    getDataString
  severity: WARNING