rules:
- id: getIntegerArrayListExtra
  pattern-either:
    - patterns:
      - pattern: $Y.$FUNC(...)
      - pattern-inside: |
          $RETVAL $FUN(...) {
            ...
            $Y = getIntent().getIntegerArrayListExtra($ARG);
            ...
          }
      - pattern-not-inside: |
          $RETVAL $FUN(...) {
            ...
            $Y = getIntent().getIntegerArrayListExtra($ARG);
            ...
            if ($Y != null) {
              ...
            }
            ...
          }
    - patterns:
      - pattern: getIntent().getIntegerArrayListExtra($ARG).$FUNC(...)
    - patterns:
      - pattern: $Y.$FUNC(...)
      - pattern-inside: |
          $RETVAL $FUN(..., Intent $X, ...) {
            ...
            $Y = (Intent $X).getIntegerArrayListExtra($ARG);
            ...
          }
      - pattern-not-inside: |
          $RETVAL $FUN(..., Intent $X, ...) {
            ...
            $Y = (Intent $X).getIntegerArrayListExtra($ARG);
            ...
            if ($Y != null) {
              ...
            }
            ...
          }
    - patterns:
      - pattern: (Intent $X).getIntegerArrayListExtra($ARG).$FUNC(...)
      - pattern-inside: |
          $RETVAL $FUN(..., Intent $X, ...) {
            ...
          }
  languages: 
    - java
  message: |
    getIntegerArrayListExtra
  severity: WARNING