rules:
  - id: EXEC
    patterns:
      - pattern: |
          @JavascriptInterface
          $RETVAL $METHOD(...) {
            ...
          }
      - metavariable-regex:
          metavariable: $METHOD
          regex: (.*EXEC.*)
    message: EXEC
    languages:
      - java
    severity: WARNING
